function plan = build_stage_br_restart_operation_plan(fault, state)
%BUILD_STAGE_BR_RESTART_OPERATION_PLAN Restart the interrupted operation.
%   Work completed before the fault is lost. After repair, the operation
%   restarts on the original machine for its full original duration.

if nargin < 2
    error('build_stage_br_restart_operation_plan:MissingInput', ...
        'fault and state are required.');
end
require_fields(fault, {'stage', 'machine_id', 'start_time', ...
    'repair_end_time', 'interrupted_operation', 'is_validated'}, ...
    'fault');
require_fields(state, {'stage', 'snapshot_time', ...
    'interrupted_operation', 'is_validated', 'is_rescheduled'}, ...
    'state');
if ~fault.is_validated || ~state.is_validated || ...
        ~strcmp(fault.stage, 'B') || ~strcmp(state.stage, 'B') || ...
        state.is_rescheduled
    error('build_stage_br_restart_operation_plan:InvalidInput', ...
        'Validated, unrescheduled Stage B inputs are required.');
end

source = state.interrupted_operation;
require_fields(source, {'machine_id', 'job', 'operation', ...
    'table_index', 'start', 'end', 'original_duration', ...
    'elapsed_processing_time', 'remaining_processing_time'}, ...
    'state.interrupted_operation');
validate_source(source, fault, state.snapshot_time);

lostSegment = segment_template();
lostSegment.segment_type = 'lost_processing_before_fault';
lostSegment.machine_id = source.machine_id;
lostSegment.job = source.job;
lostSegment.operation = source.operation;
lostSegment.start = source.start;
lostSegment.end = fault.start_time;
lostSegment.processing_time = source.elapsed_processing_time;
lostSegment.contributes_to_completion = false;

restartSegment = segment_template();
restartSegment.segment_type = 'restart_after_repair';
restartSegment.machine_id = source.machine_id;
restartSegment.job = source.job;
restartSegment.operation = source.operation;
restartSegment.start = fault.repair_end_time;
restartSegment.end = fault.repair_end_time + source.original_duration;
restartSegment.processing_time = source.original_duration;
restartSegment.contributes_to_completion = true;

plan = struct();
plan.stage = 'B-R';
plan.step = 1;
plan.rule = 'restart_on_original_machine';
plan.progress_preserved = false;
plan.restart_from_zero = true;
plan.machine_migration_allowed = false;
plan.machine_id = source.machine_id;
plan.job = source.job;
plan.operation = source.operation;
plan.original_table_index = source.table_index;
plan.original_start = source.start;
plan.original_end = source.end;
plan.original_duration = source.original_duration;
plan.lost_processing_segment = lostSegment;
plan.lost_processing_time = source.elapsed_processing_time;
plan.repair_interval = struct( ...
    'start_time', fault.start_time, ...
    'end_time', fault.repair_end_time);
plan.restart_segment = restartSegment;
plan.revised_completion_time = restartSegment.end;
plan.completion_delay = restartSegment.end - source.end;
plan.effective_completion_processing_time = source.original_duration;
plan.total_machine_processing_time = ...
    source.elapsed_processing_time + source.original_duration;
plan.successor_propagation_executed = false;
plan.is_validated = validate_plan(plan, fault);
end

function validate_source(source, fault, snapshotTime)
if source.machine_id ~= fault.machine_id || ...
        source.job ~= fault.interrupted_operation.job || ...
        source.operation ~= fault.interrupted_operation.operation || ...
        abs(snapshotTime - fault.start_time) > 1e-9 || ...
        source.elapsed_processing_time <= 0 || ...
        source.remaining_processing_time <= 0 || ...
        abs(source.elapsed_processing_time + ...
        source.remaining_processing_time - ...
        source.original_duration) > 1e-9
    error('build_stage_br_restart_operation_plan:SourceMismatch', ...
        'Interrupted-operation state is inconsistent with the fault.');
end
end

function result = validate_plan(plan, fault)
expectedDelay = fault.repair_end_time + ...
    plan.original_duration - plan.original_end;
if plan.lost_processing_segment.end > fault.start_time + 1e-9 || ...
        plan.restart_segment.start < fault.repair_end_time - 1e-9 || ...
        plan.lost_processing_segment.machine_id ~= plan.machine_id || ...
        plan.restart_segment.machine_id ~= plan.machine_id || ...
        abs(plan.restart_segment.processing_time - ...
        plan.original_duration) > 1e-9 || ...
        abs(plan.effective_completion_processing_time - ...
        plan.original_duration) > 1e-9 || ...
        abs(plan.total_machine_processing_time - ...
        plan.lost_processing_time - plan.original_duration) > 1e-9 || ...
        abs(plan.completion_delay - expectedDelay) > 1e-9 || ...
        plan.progress_preserved || ~plan.restart_from_zero || ...
        plan.machine_migration_allowed || ...
        plan.lost_processing_segment.contributes_to_completion || ...
        ~plan.restart_segment.contributes_to_completion || ...
        plan.successor_propagation_executed
    error('build_stage_br_restart_operation_plan:InvalidPlan', ...
        'The restart-on-original-machine plan is inconsistent.');
end
result = true;
end

function value = segment_template()
value = struct('segment_type', '', 'machine_id', [], ...
    'job', [], 'operation', [], 'start', [], 'end', [], ...
    'processing_time', [], 'contributes_to_completion', false);
end

function require_fields(value, fields, valueName)
for index = 1:numel(fields)
    if ~isfield(value, fields{index})
        error('build_stage_br_restart_operation_plan:MissingField', ...
            '%s.%s is required.', valueName, fields{index});
    end
end
end
