function frozen = build_stage_cs2_frozen_problem( ...
        baseline, faults, state, restartCommitments)
%BUILD_STAGE_CS2_FROZEN_PROBLEM Define C-S2 complete-rescheduling boundary.
%   Stage C's simultaneous-fault frozen boundary is reused, while the
%   interrupted commitments are restored to restart-from-zero semantics.

if nargin < 4
    error('build_stage_cs2_frozen_problem:MissingInput', ...
        'baseline, faults, state, and restartCommitments are required.');
end
validate_inputs(faults, state, restartCommitments);

adaptedCommitments = adapt_commitments(restartCommitments);
frozen = build_stage_c_simultaneous_frozen_problem( ...
    baseline, faults, state, adaptedCommitments);
frozen.stage = 'C-S2';
frozen.step = 6;
frozen.interruption_rule = 'restart_from_zero';
frozen.interrupted_commitments = restore_commitments( ...
    restartCommitments);
frozen.frozen_operations = restore_frozen_operations( ...
    frozen.frozen_operations, restartCommitments);
frozen.decoder_requirement = ...
    'stage_cs2_multiple_restart_operation_decoder';
frozen.stage_a_decoder_compatible = false;
frozen.baseline_modified = false;
frozen.is_search_executed = false;
frozen.adapted_core = 'build_stage_c_simultaneous_frozen_problem';
frozen.is_validated = validate_frozen(frozen, state, restartCommitments);
end

function adapted = adapt_commitments(commitments)
adapted = commitments;
for index = 1:numel(adapted)
    adapted(index).completed_segment = ...
        adapted(index).lost_processing_segment;
    adapted(index).resumed_segment = adapted(index).restart_segment;
end
end

function output = restore_commitments(commitments)
template = commitment_template();
output = repmat(template, 1, numel(commitments));
for index = 1:numel(commitments)
    source = commitments(index);
    output(index).event_ids = source.event_ids;
    output(index).rule = 'restart_from_zero';
    output(index).machine_id = source.machine_id;
    output(index).job = source.job;
    output(index).operation = source.operation;
    output(index).original_start = source.original_start;
    output(index).original_end = source.original_end;
    output(index).original_duration = source.original_duration;
    output(index).lost_processing_segment = ...
        source.lost_processing_segment;
    output(index).lost_processing_time = source.lost_processing_time;
    output(index).restart_segment = source.restart_segment;
    output(index).total_machine_processing_time = ...
        source.total_machine_processing_time;
    output(index).revised_completion_time = ...
        source.revised_completion_time;
    output(index).machine_migration_allowed = false;
    output(index).restart_from_zero = true;
    output(index).progress_preserved = false;
end
end

function records = restore_frozen_operations(records, commitments)
for index = 1:numel(commitments)
    commitment = commitments(index);
    match = find([records.job] == commitment.job & ...
        [records.operation] == commitment.operation);
    if numel(match) ~= 1
        error('build_stage_cs2_frozen_problem:OperationNotUnique', ...
            'Interrupted operation J%d-O%d must appear once.', ...
            commitment.job, commitment.operation);
    end
    records(match).status = 'interrupted_restart_committed';
    records(match).restart_from_zero = true;
    records(match).progress_preserved = false;
    records(match).lost_processing_time = ...
        commitment.lost_processing_time;
    records(match).total_machine_processing_time = ...
        commitment.total_machine_processing_time;
end
end

function result = validate_frozen(frozen, state, commitments)
tolerance = 1e-9;
if ~strcmp(frozen.stage, 'C-S2') || frozen.step ~= 6 || ...
        ~strcmp(frozen.interruption_rule, 'restart_from_zero') || ...
        ~strcmp(frozen.decoder_requirement, ...
        'stage_cs2_multiple_restart_operation_decoder') || ...
        frozen.stage_a_decoder_compatible || frozen.baseline_modified || ...
        frozen.is_search_executed || ...
        ~strcmp(frozen.adapted_core, ...
        'build_stage_c_simultaneous_frozen_problem') || ...
        frozen.counts.reschedulable_operations ~= ...
        state.counts.unstarted_operations
    error('build_stage_cs2_frozen_problem:InvalidFrozenProblem', ...
        'C-S2 frozen problem failed validation.');
end
for index = 1:numel(commitments)
    commitment = commitments(index);
    validate_commitment(frozen, commitment, tolerance);
end
result = true;
end

function validate_commitment(frozen, commitment, tolerance)
record = frozen.frozen_operations( ...
    [frozen.frozen_operations.job] == commitment.job & ...
    [frozen.frozen_operations.operation] == commitment.operation);
if numel(record) ~= 1 || ~record.is_interrupted || ...
        ~record.restart_from_zero || record.progress_preserved || ...
        ~strcmp(record.status, 'interrupted_restart_committed') || ...
        abs(record.end - commitment.revised_completion_time) > ...
        tolerance || ...
        abs(record.processing_duration - commitment.original_duration) > ...
        tolerance || ...
        abs(record.lost_processing_time - ...
        commitment.lost_processing_time) > tolerance || ...
        abs(record.total_machine_processing_time - ...
        commitment.total_machine_processing_time) > tolerance
    error('build_stage_cs2_frozen_problem:InvalidFrozenOperation', ...
        'Interrupted frozen operation does not match restart commitment.');
end
stored = frozen.interrupted_commitments( ...
    [frozen.interrupted_commitments.job] == commitment.job & ...
    [frozen.interrupted_commitments.operation] == ...
    commitment.operation);
if numel(stored) ~= 1 || stored.progress_preserved || ...
        ~stored.restart_from_zero || ...
        stored.machine_migration_allowed || ...
        abs(stored.lost_processing_segment.end - ...
        commitment.lost_processing_segment.end) > tolerance || ...
        abs(stored.restart_segment.start - ...
        commitment.restart_segment.start) > tolerance || ...
        abs(stored.restart_segment.processing_time - ...
        commitment.original_duration) > tolerance
    error('build_stage_cs2_frozen_problem:InvalidCommitment', ...
        'Stored C-S2 commitment does not preserve restart-from-zero rule.');
end
end

function validate_inputs(faults, state, commitments)
require_fields(state, {'stage', 'snapshot_time', ...
    'completed_operations', 'normal_in_progress_operations', ...
    'fault_in_progress_operations', 'unstarted_operations', ...
    'counts', 'is_validated', 'is_rescheduled'}, 'state');
for index = 1:numel(commitments)
    require_fields(commitments(index), {'event_ids', 'machine_id', ...
        'job', 'operation', 'original_start', 'original_end', ...
        'original_duration', 'lost_processing_segment', ...
        'lost_processing_time', 'restart_segment', ...
        'total_machine_processing_time', 'revised_completion_time', ...
        'restart_from_zero', 'progress_preserved'}, ...
        'restartCommitments');
end
if isempty(faults) || ~all([faults.is_validated]) || ...
        ~all(strcmp({faults.stage}, 'C')) || ...
        ~strcmp(state.stage, 'C') || ~state.is_validated || ...
        ~state.is_rescheduled || isempty(commitments) || ...
        ~all([commitments.restart_from_zero]) || ...
        any([commitments.progress_preserved])
    error('build_stage_cs2_frozen_problem:InvalidInput', ...
        'Validated C-S2 state and restart commitments are required.');
end
end

function value = commitment_template()
segment = struct('machine_id', [], 'original_table_index', [], ...
    'segment_order', [], 'segment_type', '', 'job', [], ...
    'operation', [], 'start', [], 'end', [], ...
    'processing_time', [], 'contributes_to_completion', false, ...
    'source_event_ids', []);
value = struct('event_ids', [], 'rule', '', 'machine_id', [], ...
    'job', [], 'operation', [], 'original_start', [], ...
    'original_end', [], 'original_duration', [], ...
    'lost_processing_segment', segment, 'lost_processing_time', [], ...
    'restart_segment', segment, 'total_machine_processing_time', [], ...
    'revised_completion_time', [], ...
    'machine_migration_allowed', false, ...
    'restart_from_zero', true, 'progress_preserved', false);
end

function require_fields(value, fields, valueName)
for index = 1:numel(fields)
    if ~isfield(value, fields{index})
        error('build_stage_cs2_frozen_problem:MissingField', ...
            '%s.%s is required.', valueName, fields{index});
    end
end
end
