function plan = build_stage_b_resume_operation_plan(fault, state)
%BUILD_STAGE_B_RESUME_OPERATION_PLAN Apply the first interruption rule.
%   Completed progress is preserved. Processing pauses during repair and
%   resumes on the original machine immediately after repair. This
%   function does not propagate the delay to successor operations.

if nargin < 2
    error('build_stage_b_resume_operation_plan:MissingInput', ...
        'fault and state are required.');
end
require_fields(fault, {'stage', 'machine_id', 'start_time', ...
    'repair_duration', 'repair_end_time', ...
    'interrupted_operation', 'is_validated'}, ...
    'fault');
require_fields(state, {'stage', 'snapshot_time', ...
    'interrupted_operation', 'is_validated', 'is_rescheduled'}, ...
    'state');
if ~fault.is_validated || ~state.is_validated || ...
        ~strcmp(fault.stage, 'B') || ~strcmp(state.stage, 'B') || ...
        state.is_rescheduled
    error('build_stage_b_resume_operation_plan:InvalidInput', ...
        'Validated, unrescheduled Stage B inputs are required.');
end

source = state.interrupted_operation;
require_fields(source, {'machine_id', 'job', 'operation', ...
    'table_index', 'start', 'end', 'original_duration', ...
    'elapsed_processing_time', 'remaining_processing_time'}, ...
    'state.interrupted_operation');
validate_source(source, fault, state.snapshot_time);

completedSegment = segment_template();
completedSegment.segment_type = 'processed_before_fault';
completedSegment.machine_id = source.machine_id;
completedSegment.job = source.job;
completedSegment.operation = source.operation;
completedSegment.start = source.start;
completedSegment.end = fault.start_time;
completedSegment.processing_time = source.elapsed_processing_time;

resumedSegment = segment_template();
resumedSegment.segment_type = 'resumed_after_repair';
resumedSegment.machine_id = source.machine_id;
resumedSegment.job = source.job;
resumedSegment.operation = source.operation;
resumedSegment.start = fault.repair_end_time;
resumedSegment.end = fault.repair_end_time + ...
    source.remaining_processing_time;
resumedSegment.processing_time = source.remaining_processing_time;

plan = struct();
plan.stage = 'B';
plan.step = 2;
plan.rule = 'resume_on_original_machine';
plan.progress_preserved = true;
plan.restart_from_zero = false;
plan.machine_migration_allowed = false;
plan.machine_id = source.machine_id;
plan.job = source.job;
plan.operation = source.operation;
plan.original_table_index = source.table_index;
plan.original_start = source.start;
plan.original_end = source.end;
plan.original_duration = source.original_duration;
plan.completed_segment = completedSegment;
plan.repair_interval = struct( ...
    'start_time', fault.start_time, ...
    'end_time', fault.repair_end_time);
plan.resumed_segment = resumedSegment;
plan.revised_completion_time = resumedSegment.end;
plan.completion_delay = resumedSegment.end - source.end;
plan.total_processing_time = completedSegment.processing_time + ...
    resumedSegment.processing_time;
plan.successor_propagation_executed = false;
plan.is_validated = validate_plan(plan, fault);
end

function validate_source(source, fault, snapshotTime)
if source.machine_id ~= fault.machine_id || ...
        source.job ~= fault.interrupted_operation.job || ...
        source.operation ~= fault.interrupted_operation.operation || ...
        abs(snapshotTime - fault.start_time) > 1e-9 || ...
        source.elapsed_processing_time <= 0 || ...
        source.remaining_processing_time <= 0 || ...
        abs(source.elapsed_processing_time + ...
        source.remaining_processing_time - ...
        source.original_duration) > 1e-9
    error('build_stage_b_resume_operation_plan:SourceMismatch', ...
        'Interrupted-operation state is inconsistent with the fault.');
end
end

function result = validate_plan(plan, fault)
if plan.completed_segment.end > fault.start_time + 1e-9 || ...
        plan.resumed_segment.start < fault.repair_end_time - 1e-9 || ...
        plan.completed_segment.machine_id ~= plan.machine_id || ...
        plan.resumed_segment.machine_id ~= plan.machine_id || ...
        abs(plan.total_processing_time - plan.original_duration) > 1e-9 || ...
        abs(plan.completion_delay - fault.repair_duration) > 1e-9 || ...
        ~plan.progress_preserved || plan.restart_from_zero || ...
        plan.machine_migration_allowed || ...
        plan.successor_propagation_executed
    error('build_stage_b_resume_operation_plan:InvalidPlan', ...
        'The resume-on-original-machine plan is inconsistent.');
end
result = true;
end

function value = segment_template()
value = struct('segment_type', '', 'machine_id', [], ...
    'job', [], 'operation', [], 'start', [], 'end', [], ...
    'processing_time', []);
end

function require_fields(value, fields, valueName)
for index = 1:numel(fields)
    if ~isfield(value, fields{index})
        error('build_stage_b_resume_operation_plan:MissingField', ...
            '%s.%s is required.', valueName, fields{index});
    end
end
end
