function commitments = build_stage_c_simultaneous_restart_commitments( ...
        faults, state)
%BUILD_STAGE_C_SIMULTANEOUS_RESTART_COMMITMENTS Build C-S2 commitments.
%   Every interrupted operation loses its pre-fault progress. After the
%   failed machine is repaired, the operation restarts on the original
%   machine for its full original processing duration.

if nargin < 2
    error('build_stage_c_simultaneous_restart_commitments:MissingInput', ...
        'faults and state are required.');
end
validate_inputs(faults, state);

interrupted = state.fault_in_progress_operations;
template = commitment_template();
commitments = repmat(template, 1, numel(interrupted));
for index = 1:numel(interrupted)
    source = interrupted(index);
    fault = find_root_fault(faults, source);
    commitment = template;
    commitment.event_ids = source.source_event_ids;
    commitment.rule = 'restart_from_zero';
    commitment.machine_id = source.machine_id;
    commitment.job = source.job;
    commitment.operation = source.operation;
    commitment.original_table_index = source.table_index;
    commitment.original_start = source.start;
    commitment.original_end = source.end;
    commitment.original_duration = source.original_duration;
    commitment.lost_processing_segment = segment_value( ...
        source, source.start, fault.start_time, ...
        'lost_processing_before_fault', false);
    commitment.lost_processing_time = source.elapsed_processing_time;
    commitment.restart_segment = segment_value( ...
        source, fault.repair_end_time, ...
        fault.repair_end_time + source.original_duration, ...
        'restart_after_repair', true);
    commitment.effective_completion_processing_time = ...
        source.original_duration;
    commitment.total_machine_processing_time = ...
        source.elapsed_processing_time + source.original_duration;
    commitment.revised_completion_time = commitment.restart_segment.end;
    commitment.completion_delay = ...
        commitment.revised_completion_time - source.end;
    commitment.machine_migration_allowed = false;
    commitment.restart_from_zero = true;
    commitment.progress_preserved = false;
    commitment.is_validated = validate_commitment( ...
        commitment, source, fault);
    commitments(index) = commitment;
end
end

function validate_inputs(faults, state)
if ~isstruct(faults) || isempty(faults) || ~isvector(faults)
    error('build_stage_c_simultaneous_restart_commitments:InvalidFaults', ...
        'faults must be a nonempty struct vector.');
end
for index = 1:numel(faults)
    require_fields(faults(index), {'stage', 'trigger_type', ...
        'machine_id', 'start_time', 'repair_end_time', ...
        'interruption_rule', 'is_validated'}, 'faults');
    if ~faults(index).is_validated || ...
            ~strcmp(faults(index).stage, 'C') || ...
            ~strcmp(faults(index).trigger_type, 'machine_failure') || ...
            ~strcmp(faults(index).interruption_rule, 'restart_from_zero')
        error(['build_stage_c_simultaneous_restart_commitments:', ...
            'InvalidFault'], ...
            'Every C-S2 fault must use restart_from_zero.');
    end
end
require_fields(state, {'stage', 'fault_in_progress_operations', ...
    'is_validated', 'is_rescheduled'}, 'state');
if ~state.is_validated || ~strcmp(state.stage, 'C') || ...
        state.is_rescheduled
    error('build_stage_c_simultaneous_restart_commitments:InvalidState', ...
        'A validated unrescheduled Stage C state is required.');
end
if numel(state.fault_in_progress_operations) ~= numel(faults)
    error(['build_stage_c_simultaneous_restart_commitments:', ...
        'InterruptedCountMismatch'], ...
        'Each simultaneous fault must directly interrupt one operation.');
end
end

function fault = find_root_fault(faults, source)
matches = find([faults.machine_id] == source.machine_id & ...
    ismember([faults.event_id], source.source_event_ids));
if numel(matches) ~= 1
    error(['build_stage_c_simultaneous_restart_commitments:', ...
        'RootFaultMismatch'], ...
        'Each interrupted operation must match exactly one fault.');
end
fault = faults(matches);
end

function segment = segment_value( ...
        source, startTime, endTime, segmentType, contributes)
segment = segment_template();
segment.machine_id = source.machine_id;
segment.original_table_index = source.table_index;
segment.segment_type = segmentType;
segment.job = source.job;
segment.operation = source.operation;
segment.start = startTime;
segment.end = endTime;
segment.processing_time = endTime - startTime;
segment.contributes_to_completion = contributes;
segment.source_event_ids = source.source_event_ids;
end

function result = validate_commitment(commitment, source, fault)
tolerance = 1e-9;
expectedDelay = fault.repair_end_time + source.original_duration - ...
    source.end;
result = abs(commitment.lost_processing_segment.start - ...
    source.start) <= tolerance && ...
    abs(commitment.lost_processing_segment.end - ...
    fault.start_time) <= tolerance && ...
    abs(commitment.restart_segment.start - ...
    fault.repair_end_time) <= tolerance && ...
    abs(commitment.restart_segment.processing_time - ...
    source.original_duration) <= tolerance && ...
    abs(commitment.lost_processing_time - ...
    source.elapsed_processing_time) <= tolerance && ...
    abs(commitment.total_machine_processing_time - ...
    source.elapsed_processing_time - source.original_duration) <= ...
    tolerance && ...
    abs(commitment.completion_delay - expectedDelay) <= tolerance && ...
    ~commitment.progress_preserved && ...
    commitment.restart_from_zero && ...
    ~commitment.machine_migration_allowed && ...
    ~commitment.lost_processing_segment.contributes_to_completion && ...
    commitment.restart_segment.contributes_to_completion;
if ~result
    error(['build_stage_c_simultaneous_restart_commitments:', ...
        'InvalidCommitment'], ...
        'The C-S2 restart commitment is inconsistent.');
end
end

function value = commitment_template()
segment = segment_template();
value = struct('event_ids', [], 'rule', '', 'machine_id', [], ...
    'job', [], 'operation', [], 'original_table_index', [], ...
    'original_start', [], 'original_end', [], ...
    'original_duration', [], 'lost_processing_segment', segment, ...
    'lost_processing_time', [], 'restart_segment', segment, ...
    'effective_completion_processing_time', [], ...
    'total_machine_processing_time', [], ...
    'revised_completion_time', [], 'completion_delay', [], ...
    'machine_migration_allowed', false, ...
    'restart_from_zero', false, ...
    'progress_preserved', true, 'is_validated', false);
end

function value = segment_template()
value = struct('machine_id', [], 'original_table_index', [], ...
    'segment_type', '', 'job', [], 'operation', [], ...
    'start', [], 'end', [], 'processing_time', [], ...
    'contributes_to_completion', false, 'source_event_ids', []);
end

function require_fields(value, fields, valueName)
for index = 1:numel(fields)
    if ~isfield(value, fields{index})
        error(['build_stage_c_simultaneous_restart_commitments:', ...
            'MissingField'], ...
            '%s.%s is required.', valueName, fields{index});
    end
end
end
