function candidate = build_stage_cs2_agv_linked_right_shift( ...
        baseline, faults, machineCandidate, agvImpact)
%BUILD_STAGE_CS2_AGV_LINKED_RIGHT_SHIFT Couple C-S2 AGV and machines.
%   The shared Stage C simultaneous-fault AGV propagation is reused after
%   mapping C-S2 restart-from-zero commitments to the Stage C commitment
%   field names. The output is restored to C-S2 semantics.

if nargin < 4
    error('build_stage_cs2_agv_linked_right_shift:MissingInput', ...
        'baseline, faults, machineCandidate, and agvImpact are required.');
end
validate_inputs(baseline, faults, machineCandidate, agvImpact);

[adaptedMachine, adaptedImpact] = adapt_inputs(machineCandidate, agvImpact);
linked = build_stage_c_simultaneous_agv_linked_right_shift( ...
    baseline, faults, adaptedMachine, adaptedImpact);

candidate = linked;
candidate.stage = 'C-S2';
candidate.step = 5;
candidate.interruption_rule = 'restart_from_zero';
candidate.interrupted_commitments = machineCandidate.interrupted_commitments;
candidate.processing_segments = restore_segment_semantics( ...
    linked.processing_segments);
candidate.restart_from_zero = true;
candidate.progress_preserved = false;
candidate.lost_processing_time = machineCandidate.lost_processing_time;
candidate.machine_only_validation = machineCandidate.validation;
candidate.validation = restore_validation(linked.validation);
candidate.is_agv_validated = true;
candidate.is_fully_validated = true;
candidate.agv_impact_required_adjustment = ...
    agvImpact.requires_agv_adjustment;
candidate.adapted_core = 'build_stage_c_simultaneous_agv_linked_right_shift';
validate_candidate(candidate, baseline, faults, agvImpact);
end

function [machineCandidate, agvImpact] = adapt_inputs( ...
        machineCandidate, agvImpact)
machineCandidate.stage = 'C';
machineCandidate.step = 6;
machineCandidate.interrupted_commitments = ...
    adapt_commitments(machineCandidate.interrupted_commitments);
agvImpact.stage = 'C';
agvImpact.step = 7;
end

function commitments = adapt_commitments(commitments)
for index = 1:numel(commitments)
    commitments(index).completed_segment = ...
        commitments(index).lost_processing_segment;
    commitments(index).resumed_segment = ...
        commitments(index).restart_segment;
end
end

function segments = restore_segment_semantics(segments)
for index = 1:numel(segments)
    segments(index).contributes_to_completion = ...
        ~strcmp(segments(index).segment_type, ...
        'lost_processing_before_fault');
end
end

function validation = restore_validation(coreValidation)
validation = coreValidation;
validation.restart_from_zero = true;
validation.progress_not_preserved = true;
validation.lost_processing_segment_preserved = true;
validation.full_restart_segment_preserved = true;
end

function validate_candidate(candidate, baseline, faults, agvImpact)
tolerance = 1e-9;
if ~strcmp(candidate.stage, 'C-S2') || candidate.step ~= 5 || ...
        ~candidate.restart_from_zero || candidate.progress_preserved || ...
        ~candidate.is_agv_validated || ~candidate.is_fully_validated || ...
        candidate.agv_impact_required_adjustment ~= ...
        agvImpact.requires_agv_adjustment || ...
        ~strcmp(candidate.adapted_core, ...
        'build_stage_c_simultaneous_agv_linked_right_shift')
    error('build_stage_cs2_agv_linked_right_shift:InvalidCandidate', ...
        'C-S2 linked right-shift candidate failed validation.');
end
if candidate.is_agv_updated && isequaln(candidate.AGVTable, baseline.AGVTable)
    error('build_stage_cs2_agv_linked_right_shift:AGVUpdateFlag', ...
        'AGV update flag is inconsistent with the AGV table.');
end
validate_restart_segments(candidate, tolerance);
validate_repair_intervals(candidate.processing_segments, faults, tolerance);
end

function validate_restart_segments(candidate, tolerance)
for index = 1:numel(candidate.interrupted_commitments)
    commitment = candidate.interrupted_commitments(index);
    selected = candidate.processing_segments( ...
        [candidate.processing_segments.job] == commitment.job & ...
        [candidate.processing_segments.operation] == ...
        commitment.operation);
    if numel(selected) ~= 2
        error('build_stage_cs2_agv_linked_right_shift:RestartSegments', ...
            'Each interrupted operation must retain two segments.');
    end
    [~, order] = sort([selected.segment_order]);
    selected = selected(order);
    if ~strcmp(selected(1).segment_type, ...
            'lost_processing_before_fault') || ...
            ~strcmp(selected(2).segment_type, ...
            'restart_after_repair') || ...
            selected(1).contributes_to_completion || ...
            ~selected(2).contributes_to_completion || ...
            abs(selected(1).start - ...
            commitment.lost_processing_segment.start) > tolerance || ...
            abs(selected(1).end - ...
            commitment.lost_processing_segment.end) > tolerance || ...
            abs(selected(2).start - ...
            commitment.restart_segment.start) > tolerance || ...
            abs(selected(2).end - ...
            commitment.restart_segment.end) > tolerance
        error('build_stage_cs2_agv_linked_right_shift:RestartSegments', ...
            'Restart-from-zero segment commitment changed.');
    end
end
end

function validate_repair_intervals(segments, faults, tolerance)
for faultIndex = 1:numel(faults)
    fault = faults(faultIndex);
    selected = segments([segments.machine_id] == fault.machine_id);
    for index = 1:numel(selected)
        overlaps = selected(index).start < ...
            fault.repair_end_time - tolerance && ...
            fault.start_time < selected(index).end - tolerance;
        if overlaps
            error('build_stage_cs2_agv_linked_right_shift:RepairOverlap', ...
                'Failed machine %d processes during repair.', ...
                fault.machine_id);
        end
    end
end
end

function validate_inputs(baseline, faults, machineCandidate, agvImpact)
require_fields(baseline, {'AGVTable', 'machineTable', 'problem'}, ...
    'baseline');
require_fields(machineCandidate, {'stage', 'step', 'interruption_rule', ...
    'interrupted_commitments', 'AGVTable', 'validation', ...
    'is_machine_validated', 'is_agv_updated', 'restart_from_zero', ...
    'progress_preserved', 'lost_processing_time'}, 'machineCandidate');
require_fields(agvImpact, {'stage', 'step', 'is_validated', ...
    'requires_agv_adjustment', 'restart_from_zero', ...
    'progress_preserved'}, 'agvImpact');
if isempty(faults) || ~all([faults.is_validated]) || ...
        ~all(strcmp({faults.stage}, 'C')) || ...
        ~strcmp(machineCandidate.stage, 'C-S2') || ...
        machineCandidate.step ~= 3 || ...
        ~strcmp(machineCandidate.interruption_rule, ...
        'restart_from_zero') || ...
        ~machineCandidate.is_machine_validated || ...
        machineCandidate.is_agv_updated || ...
        ~machineCandidate.restart_from_zero || ...
        machineCandidate.progress_preserved || ...
        ~strcmp(agvImpact.stage, 'C-S2') || agvImpact.step ~= 4 || ...
        ~agvImpact.is_validated || ~agvImpact.restart_from_zero || ...
        agvImpact.progress_preserved || ...
        ~isequaln(machineCandidate.AGVTable, baseline.AGVTable)
    error('build_stage_cs2_agv_linked_right_shift:InvalidInput', ...
        'Validated C-S2 Step 3 and Step 4 inputs are required.');
end
end

function require_fields(value, fields, valueName)
for index = 1:numel(fields)
    if ~isfield(value, fields{index})
        error('build_stage_cs2_agv_linked_right_shift:MissingField', ...
            '%s.%s is required.', valueName, fields{index});
    end
end
end
