function analysis = analyze_stage_br_agv_impact( ...
        baseline, fault, candidate)
%ANALYZE_STAGE_BR_AGV_IMPACT Identify restart-invalidated transports.
%   The established Stage B transport checks are reused after adapting
%   the machine-only candidate interface. No AGV task is modified.

if nargin < 3
    error('analyze_stage_br_agv_impact:MissingInput', ...
        'baseline, fault, and candidate are required.');
end
require_fields(candidate, {'stage', 'step', 'restart_plan', ...
    'operation_records', 'AGVTable', 'is_machine_validated', ...
    'is_agv_updated', 'restart_from_zero', ...
    'lost_processing_time'}, 'candidate');
validate_inputs(baseline, fault, candidate);

stageBCandidate = adapt_candidate(candidate);
analysis = analyze_stage_b_agv_impact( ...
    baseline, fault, stageBCandidate);
analysis.stage = 'B-R';
analysis.step = 4;
analysis.interruption_rule = candidate.restart_plan.rule;
analysis.restart_from_zero = true;
analysis.progress_preserved = false;
analysis.lost_processing_time = candidate.lost_processing_time;
analysis.interrupted_operation.restart_processing_time = ...
    candidate.restart_plan.original_duration;
analysis.analysis_core = 'analyze_stage_b_agv_impact';
analysis.is_agv_updated = false;
analysis.is_validated = validate_analysis(analysis, candidate);
end

function adapted = adapt_candidate(candidate)
% The shared analyzer reads operation times, AGVTable, and root identity.
adapted = candidate;
adapted.stage = 'B';
adapted.step = 4;
adapted.resume_plan = candidate.restart_plan;
end

function result = validate_analysis(analysis, candidate)
if ~analysis.is_validated || ~strcmp(analysis.stage, 'B-R') || ...
        analysis.step ~= 4 || analysis.is_agv_updated || ...
        ~analysis.source_agv_table_unchanged || ...
        ~analysis.restart_from_zero || analysis.progress_preserved || ...
        abs(analysis.lost_processing_time - ...
        candidate.lost_processing_time) > 1e-9 || ...
        abs(analysis.interrupted_operation.revised_completion_time - ...
        candidate.restart_plan.revised_completion_time) > 1e-9 || ...
        analysis.counts.affected_transports_total + ...
        analysis.counts.unaffected_transports <= 0
    error('analyze_stage_br_agv_impact:InvalidAnalysis', ...
        'Stage B-R AGV impact analysis failed validation.');
end
result = true;
end

function validate_inputs(baseline, fault, candidate)
if ~baseline.isFaultFreeBaseline || ~fault.is_validated || ...
        ~candidate.is_machine_validated || ...
        ~strcmp(fault.stage, 'B') || ...
        ~strcmp(candidate.stage, 'B-R') || candidate.step ~= 3 || ...
        candidate.is_agv_updated || ~candidate.restart_from_zero || ...
        ~strcmp(candidate.restart_plan.stage, 'B-R') || ...
        ~strcmp(candidate.restart_plan.rule, ...
        'restart_on_original_machine') || ...
        ~isequaln(candidate.AGVTable, baseline.AGVTable)
    error('analyze_stage_br_agv_impact:InvalidInput', ...
        'Validated Stage B-R Step 3 inputs are required.');
end
end

function require_fields(value, fields, valueName)
for index = 1:numel(fields)
    if ~isfield(value, fields{index})
        error('analyze_stage_br_agv_impact:MissingField', ...
            '%s.%s is required.', valueName, fields{index});
    end
end
end
