function analysis = analyze_stage_cs2_agv_impact( ...
        baseline, faults, candidate)
%ANALYZE_STAGE_CS2_AGV_IMPACT Identify restart-rule AGV impacts.
%   C-S2 reuses the validated Stage C simultaneous-fault transport
%   checks after adapting the machine-only restart candidate interface.
%   This step only identifies invalid or review-required transports.

if nargin < 3
    error('analyze_stage_cs2_agv_impact:MissingInput', ...
        'baseline, faults, and candidate are required.');
end
validate_inputs(baseline, faults, candidate);

adaptedCandidate = adapt_candidate(candidate);
analysis = analyze_stage_c_simultaneous_agv_impact( ...
    baseline, faults, adaptedCandidate);
analysis.stage = 'C-S2';
analysis.step = 4;
analysis.interruption_rule = candidate.interruption_rule;
analysis.restart_from_zero = true;
analysis.progress_preserved = false;
analysis.lost_processing_time = candidate.lost_processing_time;
analysis.processing_segments = summarize_restart_segments( ...
    candidate.processing_segments);
analysis.analysis_core = 'analyze_stage_c_simultaneous_agv_impact';
analysis.is_agv_updated = false;
analysis.is_validated = validate_analysis(analysis, candidate);
end

function adapted = adapt_candidate(candidate)
% The shared Stage C analyzer expects a Stage C Step 6 machine candidate.
adapted = candidate;
adapted.stage = 'C';
adapted.step = 6;
end

function summaries = summarize_restart_segments(segments)
selected = segments([segments.contributes_to_completion] | ...
    strcmp({segments.segment_type}, 'lost_processing_before_fault'));
template = struct('machine_id', [], 'job', [], 'operation', [], ...
    'segment_order', [], 'segment_type', '', 'start', [], 'end', [], ...
    'processing_time', [], 'contributes_to_completion', false, ...
    'source_event_ids', []);
summaries = repmat(template, 1, numel(selected));
for index = 1:numel(selected)
    summaries(index).machine_id = selected(index).machine_id;
    summaries(index).job = selected(index).job;
    summaries(index).operation = selected(index).operation;
    summaries(index).segment_order = selected(index).segment_order;
    summaries(index).segment_type = selected(index).segment_type;
    summaries(index).start = selected(index).start;
    summaries(index).end = selected(index).end;
    summaries(index).processing_time = selected(index).processing_time;
    summaries(index).contributes_to_completion = ...
        selected(index).contributes_to_completion;
    summaries(index).source_event_ids = selected(index).source_event_ids;
end
end

function result = validate_analysis(analysis, candidate)
tolerance = 1e-9;
if ~analysis.is_validated || ~strcmp(analysis.stage, 'C-S2') || ...
        analysis.step ~= 4 || analysis.is_agv_updated || ...
        ~analysis.source_agv_table_unchanged || ...
        ~analysis.restart_from_zero || analysis.progress_preserved || ...
        ~strcmp(analysis.interruption_rule, 'restart_from_zero') || ...
        abs(analysis.lost_processing_time - ...
        candidate.lost_processing_time) > tolerance || ...
        analysis.counts.affected_transports_total + ...
        analysis.counts.unaffected_transports <= 0
    error('analyze_stage_cs2_agv_impact:InvalidAnalysis', ...
        'C-S2 AGV impact analysis failed validation.');
end
lostSegments = analysis.processing_segments( ...
    strcmp({analysis.processing_segments.segment_type}, ...
    'lost_processing_before_fault'));
restartSegments = analysis.processing_segments( ...
    strcmp({analysis.processing_segments.segment_type}, ...
    'restart_after_repair'));
if numel(lostSegments) ~= numel(candidate.interrupted_commitments) || ...
        numel(restartSegments) ~= numel(candidate.interrupted_commitments)
    error('analyze_stage_cs2_agv_impact:InvalidSegments', ...
        'Each interrupted operation requires one lost and one restart segment.');
end
result = true;
end

function validate_inputs(baseline, faults, candidate)
require_fields(baseline, {'AGVTable', 'problem'}, 'baseline');
require_fields(candidate, {'stage', 'step', 'interruption_rule', ...
    'operation_records', 'processing_segments', ...
    'interrupted_commitments', 'AGVTable', ...
    'is_machine_validated', 'is_agv_updated', ...
    'restart_from_zero', 'progress_preserved', ...
    'lost_processing_time'}, 'candidate');
if isempty(faults) || ~all([faults.is_validated]) || ...
        ~all(strcmp({faults.stage}, 'C')) || ...
        ~candidate.is_machine_validated || ...
        ~strcmp(candidate.stage, 'C-S2') || candidate.step ~= 3 || ...
        candidate.is_agv_updated || ~candidate.restart_from_zero || ...
        candidate.progress_preserved || ...
        ~strcmp(candidate.interruption_rule, 'restart_from_zero') || ...
        ~isequaln(candidate.AGVTable, baseline.AGVTable)
    error('analyze_stage_cs2_agv_impact:InvalidInput', ...
        'Validated C-S2 Step 3 inputs are required.');
end
end

function require_fields(value, fields, valueName)
for index = 1:numel(fields)
    if ~isfield(value, fields{index})
        error('analyze_stage_cs2_agv_impact:MissingField', ...
            '%s.%s is required.', valueName, fields{index});
    end
end
end
