function context = build_stage_cseq2_impact_context(stage2)
%BUILD_STAGE_CSEQ2_IMPACT_CONTEXT Propagate the new overlapping fault.
%   C-SEQ2 keeps historical repair intervals from Step 2 while only the
%   new fault contributes fresh affected operations in this step.

if nargin < 1 || ~strcmp(stage2.step, 'C-SEQ2.2') || ...
        ~stage2.is_validated || ...
        ~isfield(stage2, 'cseq2_unavailability_context')
    error('build_stage_cseq2_impact_context:InvalidInput', ...
        'A validated C-SEQ2 Step 2 scenario is required.');
end

state = stage2.next_fault_state.state;
currentView = stage2.next_fault_state.current_plan_view;
nextFault = stage2.next_fault;
unavailabilityContext = stage2.cseq2_unavailability_context;
newImpact = identify_stage_c_simultaneous_affected_operations( ...
    currentView, state, nextFault);
merged = newImpact.affected_operations;
unaffected = remove_affected(state.unstarted_operations, merged);

context = struct();
context.stage = 'C-SEQ2';
context.step = '3';
context.input_version_id = ...
    stage2.next_fault_state.input_version_id;
context.cumulative_faults = unavailabilityContext.cumulative_faults;
context.cumulative_unavailability = ...
    unavailabilityContext.cumulative_unavailability;
context.overlap_relationships = ...
    unavailabilityContext.overlap_relationships;
context.active_previous_repairs = ...
    unavailabilityContext.active_previous_repairs;
context.new_event_impact = newImpact;
template = impact_template();
context.active_historical_impacts = template([]);
context.merged_affected_operations = merged;
context.unaffected_unstarted_operations = unaffected;
context.counts = struct( ...
    'cumulative_faults', numel(context.cumulative_faults), ...
    'cumulative_repair_intervals', ...
    context.cumulative_unavailability.interval_count, ...
    'active_previous_repairs', ...
    numel(context.active_previous_repairs), ...
    'overlap_relationships', ...
    numel(context.overlap_relationships), ...
    'active_historical_affected', 0, ...
    'new_event_affected', numel(newImpact.affected_operations), ...
    'merged_affected', numel(merged), ...
    'multi_source_operations', sum([merged.source_count] > 1), ...
    'unaffected_unstarted', numel(unaffected));
context.merge_rule = ...
    'new overlapping fault impact with historical repair intervals retained';
context.history_unchanged = true;
context.is_plan_modified = false;
context.is_rescheduled = false;
context.is_validated = validate_context(context, state, stage2);
end

function unaffected = remove_affected(unstarted, affected)
if isempty(affected)
    unaffected = unstarted;
    return
end
unaffected = unstarted(~ismember( ...
    operation_keys(unstarted), operation_keys(affected), 'rows'));
end

function keys = operation_keys(records)
if isempty(records)
    keys = zeros(0, 2);
else
    keys = [[records.job].', [records.operation].'];
end
end

function result = validate_context(context, state, stage2)
keys = operation_keys(context.merged_affected_operations);
allEventIds = [context.cumulative_faults.event_id];
result = context.cumulative_unavailability.is_validated && ...
    context.new_event_impact.is_validated && ...
    context.counts.active_previous_repairs > 0 && ...
    context.counts.overlap_relationships > 0 && ...
    context.counts.new_event_affected > 0 && ...
    context.counts.merged_affected == ...
    context.counts.new_event_affected && ...
    context.counts.merged_affected + ...
    context.counts.unaffected_unstarted == ...
    numel(state.unstarted_operations) && ...
    size(unique(keys, 'rows'), 1) == size(keys, 1) && ...
    isequal([context.cumulative_faults.event_id], ...
    [stage2.cseq2_unavailability_context.cumulative_faults.event_id]);
for index = 1:numel(context.merged_affected_operations)
    operation = context.merged_affected_operations(index);
    result = result && operation.projected_delay > 0 && ...
        operation.source_count == ...
        numel(operation.source_event_ids) && ...
        all(ismember(operation.source_event_ids, allEventIds)) && ...
        ismember(stage2.next_fault.event_id, operation.source_event_ids);
end
if ~result
    error('build_stage_cseq2_impact_context:InvalidContext', ...
        'C-SEQ2 impact context failed validation.');
end
end

function value = impact_template()
value = struct('machine_id', [], 'table_index', [], 'job', [], ...
    'operation', [], 'original_start', [], 'original_end', [], ...
    'duration', [], 'projected_start', [], 'projected_end', [], ...
    'projected_delay', [], 'source_event_ids', [], ...
    'source_count', [], 'root_job_successor', false, ...
    'root_machine_successor', false, ...
    'job_precedence_conflict', false, ...
    'machine_sequence_conflict', false);
end
