function impact = identify_stage_br_affected_operations( ...
        baseline, state, restartPlan)
%IDENTIFY_STAGE_BR_AFFECTED_OPERATIONS Propagate the restart delay.
%   The established Stage B graph propagation is reused with the full
%   restart completion time as its root. No schedule table is modified.

if nargin < 3
    error('identify_stage_br_affected_operations:MissingInput', ...
        'baseline, state, and restartPlan are required.');
end
require_fields(restartPlan, {'stage', 'step', 'rule', ...
    'machine_id', 'job', 'operation', 'original_table_index', ...
    'original_end', 'revised_completion_time', ...
    'completion_delay', 'lost_processing_time', ...
    'restart_from_zero', 'progress_preserved', ...
    'is_validated', 'successor_propagation_executed'}, ...
    'restartPlan');
validate_inputs(baseline, state, restartPlan);

propagationPlan = stage_b_propagation_plan(restartPlan);
impact = identify_stage_b_affected_operations( ...
    baseline, state, propagationPlan);
impact.stage = 'B-R';
impact.step = 2;
impact.rule = restartPlan.rule;
impact.propagation_core = ...
    'identify_stage_b_affected_operations';
impact.root_operation.restart_from_zero = true;
impact.root_operation.progress_preserved = false;
impact.root_operation.lost_processing_time = ...
    restartPlan.lost_processing_time;
impact.root_operation.restart_processing_time = ...
    restartPlan.effective_completion_processing_time;
impact.baseline_modified = false;
impact.is_rescheduled = false;
impact.is_validated = validate_impact(impact, state, restartPlan);
end

function plan = stage_b_propagation_plan(restartPlan)
% The Stage B core only reads root identity and revised completion fields.
plan = struct();
plan.stage = 'B';
plan.rule = 'resume_on_original_machine';
plan.machine_id = restartPlan.machine_id;
plan.job = restartPlan.job;
plan.operation = restartPlan.operation;
plan.original_table_index = restartPlan.original_table_index;
plan.original_end = restartPlan.original_end;
plan.revised_completion_time = ...
    restartPlan.revised_completion_time;
plan.completion_delay = restartPlan.completion_delay;
plan.successor_propagation_executed = false;
plan.is_validated = true;
end

function result = validate_impact(impact, state, restartPlan)
if ~impact.is_validated || impact.baseline_modified || ...
        impact.is_rescheduled || ...
        abs(impact.root_operation.revised_end - ...
        restartPlan.revised_completion_time) > 1e-9 || ...
        abs(impact.root_operation.completion_delay - ...
        restartPlan.completion_delay) > 1e-9 || ...
        abs(impact.root_operation.lost_processing_time - ...
        restartPlan.lost_processing_time) > 1e-9 || ...
        impact.counts.affected_total + ...
        impact.counts.unaffected_unstarted ~= ...
        numel(state.unstarted_operations)
    error('identify_stage_br_affected_operations:InvalidImpact', ...
        'Stage B-R impact propagation failed validation.');
end
result = true;
end

function validate_inputs(baseline, state, restartPlan)
if ~baseline.isFaultFreeBaseline || ~state.is_validated || ...
        state.is_rescheduled || ~restartPlan.is_validated || ...
        ~strcmp(state.stage, 'B') || ...
        ~strcmp(restartPlan.stage, 'B-R') || restartPlan.step ~= 1 || ...
        ~strcmp(restartPlan.rule, 'restart_on_original_machine') || ...
        ~restartPlan.restart_from_zero || ...
        restartPlan.progress_preserved || ...
        restartPlan.successor_propagation_executed
    error('identify_stage_br_affected_operations:InvalidInput', ...
        'Validated Stage B-R restart inputs are required.');
end
if restartPlan.machine_id ~= ...
        state.interrupted_operation.machine_id || ...
        restartPlan.job ~= state.interrupted_operation.job || ...
        restartPlan.operation ~= ...
        state.interrupted_operation.operation
    error('identify_stage_br_affected_operations:RootMismatch', ...
        'Restart plan and interrupted state must identify the same root.');
end
end

function require_fields(value, fields, valueName)
for index = 1:numel(fields)
    if ~isfield(value, fields{index})
        error('identify_stage_br_affected_operations:MissingField', ...
            '%s.%s is required.', valueName, fields{index});
    end
end
end
