function fault = validate_processing_fault_event(fault, baseline)
%VALIDATE_PROCESSING_FAULT_EVENT Validate a Stage B in-process fault.

requiredFault = {'event_id', 'stage', 'trigger_type', 'machine_id', ...
    'start_time', 'repair_duration', 'repair_end_time', ...
    'trigger_job', 'trigger_operation', 'interruption_fraction', ...
    'interruption_rule', 'interrupted_operation', 'is_validated'};
require_fields(fault, requiredFault, 'fault');
require_fields(baseline, {'machineTable', 'isFaultFreeBaseline'}, ...
    'baseline');
if ~baseline.isFaultFreeBaseline || ...
        ~strcmp(fault.stage, 'B') || ...
        ~strcmp(fault.trigger_type, 'operation_processing')
    error('validate_processing_fault_event:InvalidEvent', ...
        'A fault-free baseline and Stage B processing event are required.');
end
if fault.machine_id < 1 || ...
        fault.machine_id > numel(baseline.machineTable)
    error('validate_processing_fault_event:InvalidMachine', ...
        'fault.machine_id is outside the machine table.');
end
if fault.repair_duration <= 0 || ...
        abs(fault.repair_end_time - fault.start_time - ...
        fault.repair_duration) > 1e-9
    error('validate_processing_fault_event:InvalidRepairInterval', ...
        'The repair interval is invalid.');
end

interrupted = fault.interrupted_operation;
requiredInterrupted = {'machine_id', 'job', 'operation', ...
    'original_start', 'original_end', 'original_duration', ...
    'elapsed_processing_time', 'remaining_processing_time', ...
    'progress_ratio'};
require_fields(interrupted, requiredInterrupted, ...
    'fault.interrupted_operation');

blocks = baseline.machineTable{fault.machine_id};
matches = find([blocks.job] == fault.trigger_job & ...
    [blocks.opera] == fault.trigger_operation);
if numel(matches) ~= 1
    error('validate_processing_fault_event:OperationNotUnique', ...
        'The interrupted operation must appear exactly once.');
end
block = blocks(matches);
if ~(block.start < fault.start_time && fault.start_time < block.end)
    error('validate_processing_fault_event:NotDuringProcessing', ...
        'The fault time must lie strictly inside the operation.');
end

expectedDuration = block.end - block.start;
expectedElapsed = fault.start_time - block.start;
expectedRemaining = block.end - fault.start_time;
values = [ ...
    interrupted.original_start - block.start, ...
    interrupted.original_end - block.end, ...
    interrupted.original_duration - expectedDuration, ...
    interrupted.elapsed_processing_time - expectedElapsed, ...
    interrupted.remaining_processing_time - expectedRemaining, ...
    interrupted.progress_ratio - expectedElapsed / expectedDuration, ...
    fault.interruption_fraction - expectedElapsed / expectedDuration];
if interrupted.machine_id ~= fault.machine_id || ...
        interrupted.job ~= fault.trigger_job || ...
        interrupted.operation ~= fault.trigger_operation || ...
        max(abs(values)) > 1e-9 || ...
        abs(interrupted.elapsed_processing_time + ...
        interrupted.remaining_processing_time - ...
        interrupted.original_duration) > 1e-9
    error('validate_processing_fault_event:ProgressMismatch', ...
        'Interrupted-operation progress is inconsistent.');
end
if ~strcmp(fault.interruption_rule, 'unresolved')
    error('validate_processing_fault_event:RulePrematurelyResolved', ...
        'Stage B Step 1 must not select an interruption rule.');
end
fault.is_validated = true;
end

function require_fields(value, fields, valueName)
for index = 1:numel(fields)
    if ~isfield(value, fields{index})
        error('validate_processing_fault_event:MissingField', ...
            '%s.%s is required.', valueName, fields{index});
    end
end
end
