function fault = validate_completion_fault_event(fault, baseline)
%VALIDATE_COMPLETION_FAULT_EVENT Validate a Stage A completion-time fault.

requiredFaultFields = {'event_id', 'stage', 'trigger_type', ...
    'machine_id', 'start_time', 'repair_duration', 'repair_end_time', ...
    'trigger_job', 'trigger_operation', 'trigger_operation_start', ...
    'trigger_operation_end', 'interrupted_operation', 'is_validated'};
require_fields(fault, requiredFaultFields, 'fault');
require_fields(baseline, {'machineTable', 'problem', ...
    'isFaultFreeBaseline'}, 'baseline');

if ~baseline.isFaultFreeBaseline
    error('validate_completion_fault_event:InvalidBaseline', ...
        'baseline must be a fault-free normal schedule.');
end
if ~strcmp(fault.stage, 'A') || ...
        ~strcmp(fault.trigger_type, 'operation_completion')
    error('validate_completion_fault_event:InvalidEventType', ...
        'Stage A requires an operation_completion fault event.');
end
if fault.machine_id < 1 || ...
        fault.machine_id > numel(baseline.machineTable)
    error('validate_completion_fault_event:InvalidMachine', ...
        'fault.machine_id is outside baseline.machineTable.');
end
if fault.repair_duration <= 0 || ~isfinite(fault.repair_duration)
    error('validate_completion_fault_event:InvalidRepairDuration', ...
        'fault.repair_duration must be positive and finite.');
end
if abs(fault.repair_end_time - ...
        (fault.start_time + fault.repair_duration)) > 1e-9
    error('validate_completion_fault_event:InvalidRepairEnd', ...
        'repair_end_time must equal start_time + repair_duration.');
end
if ~isempty(fault.interrupted_operation)
    error('validate_completion_fault_event:InterruptedOperation', ...
        'Stage A completion-time faults cannot interrupt an operation.');
end

blocks = baseline.machineTable{fault.machine_id};
triggerMatches = false(1, numel(blocks));
for blockIndex = 1:numel(blocks)
    block = blocks(blockIndex);
    triggerMatches(blockIndex) = ...
        block.job == fault.trigger_job && ...
        block.opera == fault.trigger_operation && ...
        abs(block.end - fault.start_time) <= 1e-9;

    if block.job ~= 0 && ...
            block.start < fault.start_time && ...
            fault.start_time < block.end
        error('validate_completion_fault_event:FailureDuringProcessing', ...
            ['The selected failure time lies inside operation ', ...
            'J%d-O%d on machine %d.'], ...
            block.job, block.opera, fault.machine_id);
    end
end

if sum(triggerMatches) ~= 1
    error('validate_completion_fault_event:TriggerNotFound', ...
        'The trigger operation does not end at fault.start_time.');
end

fault.is_validated = true;
end

function require_fields(value, fields, valueName)
for index = 1:numel(fields)
    if ~isfield(value, fields{index})
        error('validate_completion_fault_event:MissingField', ...
            '%s.%s is required.', valueName, fields{index});
    end
end
end
