function config = stage_c_final_audit_matrix_config(projectRoot)
%STAGE_C_FINAL_AUDIT_MATRIX_CONFIG Define Stage C Step 17.1.
%   The matrix separates implemented runnable scenarios from planned
%   validation gaps. It does not launch experiments or create outputs.

if nargin < 1
    projectRoot = fileparts(fileparts(mfilename('fullpath')));
end

config = struct();
config.step = '17.1';
config.audit_scope = 'stage_c_final_scenario_matrix';
config.random_seeds = [11, 22, 33, 42, 55];
config.completion_time_weight = 0.9;
config.sequence_deviation_weight = 0.1;
config.formal_population_size = 10;
config.formal_generations = 100;
config.no_improvement_generations = 10;
config.max_runtime_seconds = 30;
config.output_root = fullfile(projectRoot, 'outputs', ...
    'stage_c_final_audit_matrix');

config.scenarios = [
    scenario_value( ...
    'C-S1', ...
    'simultaneous_two_machine_faults', ...
    'resume_remaining', ...
    true, ...
    'implemented', ...
    'Stage C simultaneous-fault resume flow already has formal search and combination selection.')
    scenario_value( ...
    'C-S2', ...
    'simultaneous_two_machine_faults', ...
    'restart_from_zero', ...
    false, ...
    'not_implemented', ...
    'Stage C simultaneous restart-from-zero rule has not been implemented; B-R covers single-machine restart comparison only.')
    scenario_value( ...
    'C-SEQ1', ...
    'sequential_faults_non_overlapping_repairs', ...
    'resume_remaining', ...
    true, ...
    'implemented', ...
    'Stage C sequential non-overlap resume flow completed through formal search and combination selection.')
    scenario_value( ...
    'C-SEQ2', ...
    'sequential_faults_overlapping_repairs', ...
    'resume_remaining', ...
    false, ...
    'planned', ...
    'Overlapping repair scenario still needs dedicated screening and active previous-repair validation.')
    ];

config.required_audits = { ...
    'machine_constraints', ...
    'job_precedence', ...
    'agv_non_overlap', ...
    'transport_arrival', ...
    'repair_intervals', ...
    'interrupted_commitments', ...
    'final_unload', ...
    'energy_closure', ...
    'combined_selection'};
config.is_validated = validate_config(config);
end

function scenario = scenario_value( ...
        id, relation, interruptionRule, runReady, status, note)
scenario = struct();
scenario.id = id;
scenario.fault_relation = relation;
scenario.interruption_rule = interruptionRule;
scenario.run_ready = runReady;
scenario.implementation_status = status;
scenario.note = note;
end

function result = validate_config(config)
scenarioIds = {config.scenarios.id};
expectedIds = {'C-S1', 'C-S2', 'C-SEQ1', 'C-SEQ2'};
hasValidOutputRoot = ischar(config.output_root) && ...
    ~isempty(config.output_root);
result = isequal(scenarioIds, expectedIds) && ...
    numel(config.random_seeds) == 5 && ...
    all(config.random_seeds == floor(config.random_seeds)) && ...
    abs(config.completion_time_weight + ...
    config.sequence_deviation_weight - 1) <= 1e-9 && ...
    config.formal_population_size == 10 && ...
    config.formal_generations == 100 && ...
    config.no_improvement_generations == 10 && ...
    config.max_runtime_seconds == 30 && hasValidOutputRoot;
if ~result
    error('stage_c_final_audit_matrix_config:InvalidConfig', ...
        'Stage C final audit matrix is inconsistent.');
end
end
