function result = run_stage_br_step_12_multiseed(stage11)
%RUN_STAGE_BR_STEP_12_MULTISEED Run the formal repeated Stage B-R search.
%   This function runs five searches and writes a new output directory.

if nargin < 1 || stage11.step ~= 11 || ~stage11.is_validated
    error('run_stage_br_step_12_multiseed:InvalidInput', ...
        'A validated Stage B-R Step 11 result is required.');
end
projectRoot = fileparts(fileparts(mfilename('fullpath')));
originalPath = path;
cleanupPath = onCleanup(@() path(originalPath));
addpath(fullfile(projectRoot, 'configs'));
addpath(fullfile(projectRoot, 'scripts'));
addpath(fullfile(projectRoot, 'src', 'evaluation'));
addpath(fullfile(projectRoot, 'src', 'rescheduling'));
addpath(fullfile(projectRoot, 'src', 'scheduling'));

config = stage_br_step_12_config(projectRoot);
frozenScenario = run_stage_br_frozen_problem(stage11.baseline);
validate_same_scenario(stage11, frozenScenario);
runs = repmat(run_template(), 1, numel(config.seeds));
for index = 1:numel(config.seeds)
    seed = config.seeds(index);
    rng(seed);
    search = search_stage_br_complete_reschedule( ...
        stage11.baseline, frozenScenario.frozen_problem, ...
        search_options(config));
    selection = select_stage_br_combined_strategy( ...
        stage11.baseline, stage11.state, ...
        stage11.linked_right_shift, search, ...
        combination_config(config));
    runs(index) = summarize_run(seed, search, selection);
end

result = struct();
result.stage = 'B-R';
result.step = 12;
result.config = config;
result.runs = runs;
result.run_count = numel(runs);
result.restart_from_zero = true;
result.multiseed_search_executed = true;
result.is_validated = all([runs.is_validated]);
result.output_directory = create_unique_output_directory( ...
    config.output_root);
save_outputs(result.output_directory, result, config);
fprintf('Stage B-R Step 12 multiseed experiment completed.\n');
fprintf('Output directory: %s\n', result.output_directory);
end

function options = search_options(config)
fields = {'population_size', 'generations', ...
    'crossover_probability', 'mutation_probability', ...
    'tournament_size', 'no_improvement_generations', ...
    'max_runtime_seconds', 'improvement_tolerance'};
options = struct();
for index = 1:numel(fields)
    options.(fields{index}) = config.(fields{index});
end
end

function value = combination_config(config)
value = struct('completion_time_weight', ...
    config.completion_time_weight, ...
    'sequence_deviation_weight', ...
    config.sequence_deviation_weight, ...
    'tie_tolerance', config.tie_tolerance);
end

function value = summarize_run(seed, search, selection)
value = run_template();
value.seed = seed;
value.stop_reason = search.stop_reason;
value.completed_generations = search.completed_generations;
value.runtime_seconds = search.runtime_seconds;
value.pareto_count = numel(search.pareto_front);
value.selected_strategy = selection.selected_strategy;
value.selected_final_unload_makespan = ...
    selection.selected_metrics.candidate_makespan;
value.selected_tD = selection.selected_metrics.tD;
value.selected_SD = selection.selected_metrics.SD;
value.selected_Y = selection.selected_metrics.Y;
value.restart_from_zero = search.restart_from_zero;
value.is_validated = search.is_validated && selection.is_validated;
end

function value = run_template()
value = struct('seed', [], 'stop_reason', '', ...
    'completed_generations', [], 'runtime_seconds', [], ...
    'pareto_count', [], 'selected_strategy', '', ...
    'selected_final_unload_makespan', [], 'selected_tD', [], ...
    'selected_SD', [], 'selected_Y', [], ...
    'restart_from_zero', false, 'is_validated', false);
end

function validate_same_scenario(stage11, frozenScenario)
sameFault = stage11.fault.machine_id == ...
    frozenScenario.fault.machine_id && ...
    abs(stage11.fault.start_time - ...
    frozenScenario.fault.start_time) <= 1e-9 && ...
    abs(stage11.fault.repair_end_time - ...
    frozenScenario.fault.repair_end_time) <= 1e-9;
sameInterrupted = stage11.restart_plan.job == ...
    frozenScenario.restart_plan.job && ...
    stage11.restart_plan.operation == ...
    frozenScenario.restart_plan.operation && ...
    stage11.restart_plan.machine_id == ...
    frozenScenario.restart_plan.machine_id && ...
    stage11.restart_plan.restart_from_zero && ...
    frozenScenario.restart_plan.restart_from_zero && ...
    abs(stage11.restart_plan.lost_processing_time - ...
    frozenScenario.restart_plan.lost_processing_time) <= 1e-9;
if ~sameFault || ~sameInterrupted
    error('run_stage_br_step_12_multiseed:ScenarioMismatch', ...
        'The rebuilt frozen problem does not match Stage B-R Step 11.');
end
end

function outputDirectory = create_unique_output_directory(outputRoot)
if ~exist(outputRoot, 'dir')
    mkdir(outputRoot);
end
timestamp = datestr(now, 'yyyymmdd_HHMMSS');
outputDirectory = fullfile(outputRoot, timestamp);
suffix = 1;
while exist(outputDirectory, 'dir')
    outputDirectory = fullfile(outputRoot, ...
        sprintf('%s_%02d', timestamp, suffix));
    suffix = suffix + 1;
end
mkdir(outputDirectory);
end

function save_outputs(outputDirectory, result, config)
save(fullfile(outputDirectory, 'result.mat'), ...
    'result', 'config', '-v7');
runs = result.runs;
value = table([runs.seed].', {runs.stop_reason}.', ...
    [runs.completed_generations].', [runs.runtime_seconds].', ...
    [runs.pareto_count].', {runs.selected_strategy}.', ...
    [runs.selected_final_unload_makespan].', ...
    [runs.selected_tD].', [runs.selected_SD].', ...
    [runs.selected_Y].', [runs.restart_from_zero].', ...
    'VariableNames', {'seed', 'stop_reason', ...
    'completed_generations', 'runtime_seconds', 'pareto_count', ...
    'selected_strategy', 'selected_final_unload_makespan', ...
    'selected_tD', 'selected_SD', 'selected_Y', ...
    'restart_from_zero'});
writetable(value, fullfile(outputDirectory, 'multiseed_summary.csv'));
end
