function scenario = run_stage_br_reschedule_operators(baseline)
%RUN_STAGE_BR_RESCHEDULE_OPERATORS Build and vary a Stage B-R population.
%   This entry performs restricted initialization and one variation pass.
%   It does not evaluate fitness, select survivors, or run generations.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
originalPath = path;
cleanupPath = onCleanup(@() path(originalPath));
addpath(fullfile(projectRoot, 'scripts'));
addpath(fullfile(projectRoot, 'src', 'rescheduling'));

if nargin < 1
    scenario = run_stage_br_frozen_problem();
else
    scenario = run_stage_br_frozen_problem(baseline);
end

seedDecision = build_stage_a_baseline_seed_decision( ...
    scenario.baseline, scenario.frozen_problem);
rng(scenario.baseline.seed);
scenario.operator_config = struct( ...
    'population_size', 6, ...
    'crossover_probability', 0.8, ...
    'mutation_probability', 0.2, ...
    'random_seed', scenario.baseline.seed);
scenario.operator_population = ...
    initialize_stage_a_reschedule_population( ...
    scenario.baseline, scenario.frozen_problem, ...
    scenario.operator_config.population_size, seedDecision);
scenario.operator_offspring = ...
    vary_stage_a_reschedule_population( ...
    scenario.operator_population, scenario.baseline, ...
    scenario.frozen_problem, ...
    scenario.operator_config.crossover_probability, ...
    scenario.operator_config.mutation_probability);
scenario.step = 8;
scenario.is_operator_contract_built = true;
scenario.is_fitness_evaluated = false;
scenario.is_search_executed = false;
scenario.is_rescheduled = false;
end

