function combined = run_stage_c_combination_selection(searchScenario)
%RUN_STAGE_C_COMBINATION_SELECTION Reuse one Stage C completed search.
%   The search is not rerun. The linked right shift is rebuilt from the
%   exact same baseline and dynamically selected simultaneous faults.

if nargin < 1 || ...
        ~isfield(searchScenario, 'complete_reschedule_search')
    error('run_stage_c_combination_selection:MissingSearch', ...
        'A scenario containing complete_reschedule_search is required.');
end

projectRoot = fileparts(fileparts(mfilename('fullpath')));
originalPath = path;
cleanupPath = onCleanup(@() path(originalPath));
addpath(fullfile(projectRoot, 'configs'));
addpath(fullfile(projectRoot, 'scripts'));
addpath(fullfile(projectRoot, 'src', 'evaluation'));
addpath(fullfile(projectRoot, 'src', 'rescheduling'));

rightScenario = run_stage_c_simultaneous_agv_linked_right_shift( ...
    searchScenario.baseline);
validate_same_scenario(searchScenario, rightScenario);
rightShift = evaluate_stage_c_right_shift_energy( ...
    rightScenario.baseline, rightScenario.linked_right_shift);

combined = rightScenario;
combined.linked_right_shift = rightShift;
combined.frozen_problem = searchScenario.frozen_problem;
combined.complete_reschedule_search = ...
    searchScenario.complete_reschedule_search;
combined.combination_config = stage_c_combination_config();
combined.combined_selection = select_stage_c_combined_strategy( ...
    combined.baseline, combined.state, rightShift, ...
    combined.complete_reschedule_search, combined.combination_config);
combined.right_shift_audit = audit_stage_c_rescheduling_candidate( ...
    rightShift, combined.faults, ...
    rightShift.interrupted_commitments, 'partial_right_shift');
front = combined.complete_reschedule_search.pareto_front;
combined.complete_reschedule_audits = repmat( ...
    combined.right_shift_audit, 1, numel(front));
for index = 1:numel(front)
    combined.complete_reschedule_audits(index) = ...
        audit_stage_c_rescheduling_candidate( ...
        front(index).candidate, combined.faults, ...
        combined.frozen_problem.interrupted_commitments, ...
        'complete_rescheduling');
end
combined.step = 11;
combined.is_combination_evaluated = true;
combined.all_constraint_audits_validated = ...
    combined.right_shift_audit.is_validated && ...
    all([combined.complete_reschedule_audits.is_validated]);
combined.all_energy_audits_complete = ...
    combined.right_shift_audit.energy_audit_complete && ...
    all([combined.complete_reschedule_audits.energy_audit_complete]);
combined.is_validated = combined.is_validated && ...
    combined.combined_selection.is_validated && ...
    combined.all_constraint_audits_validated && ...
    combined.all_energy_audits_complete;
end

function validate_same_scenario(searchScenario, rightScenario)
if ~isequal(searchScenario.baseline.chrom, rightScenario.baseline.chrom) || ...
        abs(searchScenario.baseline.makespan - ...
        rightScenario.baseline.makespan) > 1e-9 || ...
        numel(searchScenario.faults) ~= numel(rightScenario.faults)
    error('run_stage_c_combination_selection:ScenarioMismatch', ...
        'Both strategies must share one baseline and fault group.');
end
for index = 1:numel(searchScenario.faults)
    left = searchScenario.faults(index);
    right = rightScenario.faults(index);
    if left.event_id ~= right.event_id || ...
            left.machine_id ~= right.machine_id || ...
            abs(left.start_time - right.start_time) > 1e-9 || ...
            abs(left.repair_end_time - right.repair_end_time) > 1e-9
        error('run_stage_c_combination_selection:ScenarioMismatch', ...
            'Simultaneous fault events differ between strategies.');
    end
end
end
