function combined = run_stage_cseq2_combination_selection(searchScenario)
%RUN_STAGE_CSEQ2_COMBINATION_SELECTION Build C-SEQ2 Step 13.
%   Reuse one C-SEQ2 search scenario and compare complete-rescheduling
%   Pareto candidates with the matching AGV-linked right shift.

if nargin < 1 || ...
        ~isfield(searchScenario, 'cseq2_complete_reschedule_search')
    error('run_stage_cseq2_combination_selection:MissingSearch', ...
        'A scenario containing cseq2_complete_reschedule_search is required.');
end

projectRoot = fileparts(fileparts(mfilename('fullpath')));
originalPath = path;
cleanupPath = onCleanup(@() path(originalPath));
addpath(fullfile(projectRoot, 'configs'));
addpath(fullfile(projectRoot, 'src', 'evaluation'));
addpath(fullfile(projectRoot, 'src', 'rescheduling'));

currentView = searchScenario.next_fault_state.current_plan_view;
currentView = attach_current_plan_energy(currentView, searchScenario);
rightShift = evaluate_stage_c_right_shift_energy( ...
    currentView, searchScenario.cseq2_linked_right_shift);

combined = searchScenario;
combined.cseq2_linked_right_shift = rightShift;
combined.cseq2_complete_reschedule_search = ...
    searchScenario.cseq2_complete_reschedule_search;
combined.combination_config = stage_c_combination_config();
combined.combined_selection = select_stage_c_combined_strategy( ...
    currentView, combined.next_fault_state.state, rightShift, ...
    combined.cseq2_complete_reschedule_search, ...
    combined.combination_config);
combined.right_shift_audit = audit_stage_c_rescheduling_candidate( ...
    rightShift, combined.next_fault, ...
    rightShift.interrupted_commitments, 'partial_right_shift');
front = combined.cseq2_complete_reschedule_search.pareto_front;
combined.complete_reschedule_audits = repmat( ...
    combined.right_shift_audit, 1, numel(front));
for index = 1:numel(front)
    combined.complete_reschedule_audits(index) = ...
        audit_stage_c_rescheduling_candidate( ...
        front(index).candidate, combined.next_fault, ...
        combined.cseq2_frozen_problem.interrupted_commitments, ...
        'complete_rescheduling');
end
combined.step = 'C-SEQ2.13';
combined.substep = '13';
combined.is_combination_evaluated = true;
combined.all_constraint_audits_validated = ...
    combined.right_shift_audit.is_validated && ...
    all([combined.complete_reschedule_audits.is_validated]);
combined.all_energy_audits_complete = ...
    combined.right_shift_audit.energy_audit_complete && ...
    all([combined.complete_reschedule_audits.energy_audit_complete]);
combined.is_validated = combined.is_validated && ...
    combined.combined_selection.is_validated && ...
    combined.all_constraint_audits_validated && ...
    combined.all_energy_audits_complete;
end

function currentView = attach_current_plan_energy(currentView, scenario)
if isfield(currentView, 'agvEnergy') && ...
        isscalar(currentView.agvEnergy) && isfinite(currentView.agvEnergy)
    return
end
if isfield(scenario, 'plan_version_history') && ...
        isfield(scenario.plan_version_history, 'versions') && ...
        ~isempty(scenario.plan_version_history.versions)
    activePlan = scenario.plan_version_history.versions(end).plan;
    if isfield(activePlan, 'agv_energy') && ...
            isscalar(activePlan.agv_energy) && isfinite(activePlan.agv_energy)
        currentView.agvEnergy = activePlan.agv_energy;
    end
end
end
