function scenario = run_stage_a_rebuilt_rescheduling_chain(normalScenario)
%RUN_STAGE_A_REBUILT_RESCHEDULING_CHAIN Rebuild the Stage A chain.

if nargin < 1
    error('run_stage_a_rebuilt_rescheduling_chain:MissingInput', ...
        'The Stage A Step 10 normalScenario is required.');
end

projectRoot = fileparts(fileparts(mfilename('fullpath')));
originalPath = path;
cleanupPath = onCleanup(@() path(originalPath));

addpath(fullfile(projectRoot, 'scripts'));
addpath(fullfile(projectRoot, 'src', 'impact'));
addpath(fullfile(projectRoot, 'src', 'rescheduling'));
addpath(fullfile(projectRoot, 'src', 'state'));

stage11 = run_stage_a_optimized_baseline_fault_screening( ...
    normalScenario);
baseline = stage11.baseline;
fault = stage11.selected_fault;
machineTableBefore = baseline.machineTable;
agvTableBefore = baseline.AGVTable;

state = extract_stage_a_state(baseline, fault);
impact = identify_stage_a_affected_operations( ...
    baseline, fault, state);
rightShift = build_stage_a_machine_right_shift( ...
    baseline, fault, state, impact);
agvImpact = analyze_stage_a_agv_impact(baseline, rightShift);
linkedRightShift = build_stage_a_agv_linked_right_shift( ...
    baseline, fault, rightShift, agvImpact);
frozenProblem = build_stage_a_frozen_problem( ...
    baseline, fault, state);

scenario = struct();
scenario.stage = 'A';
scenario.step = 12;
scenario.normal_scenario = normalScenario;
scenario.stage11 = stage11;
scenario.baseline = baseline;
scenario.fault = fault;
scenario.state = state;
scenario.impact = impact;
scenario.right_shift = rightShift;
scenario.agv_impact = agvImpact;
scenario.linked_right_shift = linkedRightShift;
scenario.frozen_problem = frozenProblem;
scenario.complete_reschedule_search = [];
scenario.is_search_executed = false;
scenario.is_combination_evaluated = false;
scenario.baseline_modified = ...
    ~isequaln(machineTableBefore, baseline.machineTable) || ...
    ~isequaln(agvTableBefore, baseline.AGVTable);
scenario.is_validated = validate_chain(scenario);

print_summary(scenario);
end

function result = validate_chain(scenario)
baseline = scenario.baseline;
fault = scenario.fault;
selected = scenario.stage11.selected_candidate;

sameFault = selected.machine_id == fault.machine_id && ...
    selected.trigger_job == fault.trigger_job && ...
    selected.trigger_operation == fault.trigger_operation && ...
    abs(selected.fault_time - fault.start_time) <= 1e-9;
sameSnapshot = abs(scenario.state.snapshot_time - ...
    fault.start_time) <= 1e-9;
sameRepairInterval = ...
    scenario.impact.unavailable_interval.machine_id == ...
    fault.machine_id && ...
    abs(scenario.impact.unavailable_interval.start_time - ...
    fault.start_time) <= 1e-9 && ...
    abs(scenario.impact.unavailable_interval.end_time - ...
    fault.repair_end_time) <= 1e-9;
sameFrozenBoundary = ...
    abs(scenario.frozen_problem.snapshot_time - ...
    fault.start_time) <= 1e-9 && ...
    scenario.frozen_problem.repair_interval.machine_id == ...
    fault.machine_id && ...
    abs(scenario.frozen_problem.repair_interval.end_time - ...
    fault.repair_end_time) <= 1e-9;

result = baseline.isFaultFreeBaseline && ...
    abs(baseline.makespan - ...
    scenario.normal_scenario.optimized_baseline.makespan) <= 1e-9 && ...
    sameFault && sameSnapshot && sameRepairInterval && ...
    sameFrozenBoundary && scenario.state.is_validated && ...
    scenario.impact.is_validated && ...
    scenario.impact.counts.directly_affected > 0 && ...
    scenario.right_shift.is_machine_validated && ...
    scenario.agv_impact.is_validated && ...
    scenario.linked_right_shift.is_fully_validated && ...
    scenario.frozen_problem.is_validated && ...
    ~scenario.frozen_problem.is_search_executed && ...
    ~scenario.baseline_modified;
if ~result
    error('run_stage_a_rebuilt_rescheduling_chain:InvalidChain', ...
        'The rebuilt Stage A rescheduling chain failed validation.');
end
end

function print_summary(scenario)
fault = scenario.fault;
fprintf('Stage A Step 12 rebuilt rescheduling chain\n');
fprintf('baseline makespan: %.6g\n', scenario.baseline.makespan);
fprintf('fault: J%d-O%d, M%d, tf=%.6g, tr=%.6g\n', ...
    fault.trigger_job, fault.trigger_operation, fault.machine_id, ...
    fault.start_time, fault.repair_duration);
fprintf('affected operations: %d, directly affected: %d\n', ...
    scenario.impact.counts.affected_total, ...
    scenario.impact.counts.directly_affected);
fprintf('AGV adjustment required: %d, affected transports: %d\n', ...
    scenario.agv_impact.requires_agv_adjustment, ...
    scenario.agv_impact.counts.affected_transports_total);
fprintf('linked right shift makespan: %.6g\n', ...
    scenario.linked_right_shift.machine_makespan);
fprintf('frozen operations: %d, reschedulable operations: %d\n', ...
    scenario.frozen_problem.counts.frozen_operations, ...
    scenario.frozen_problem.counts.reschedulable_operations);
fprintf('complete search executed: %d\n', ...
    scenario.is_search_executed);
end
