function result = run_stage_cseq2_step_14_analysis(stage13)
%RUN_STAGE_CSEQ2_STEP_14_ANALYSIS Audit C-SEQ2 candidates and scan weights.

if nargin < 1 || ~isfield(stage13, 'combined_selection') || ...
        ~strcmp(stage13.step, 'C-SEQ2.13') || ~stage13.is_validated
    error('run_stage_cseq2_step_14_analysis:InvalidInput', ...
        'A validated C-SEQ2 Step 13 result is required.');
end
projectRoot = fileparts(fileparts(mfilename('fullpath')));
originalPath = path;
cleanupPath = onCleanup(@() path(originalPath));
addpath(fullfile(projectRoot, 'configs'));
addpath(fullfile(projectRoot, 'src', 'evaluation'));

config = stage_cseq2_step_14_config(projectRoot);
currentView = stage13.next_fault_state.current_plan_view;
currentView = attach_current_plan_energy(currentView, stage13);
rightShift = evaluate_stage_c_right_shift_energy( ...
    currentView, stage13.cseq2_linked_right_shift);
weightAnalysis = analyze_stage_cs2_weight_sensitivity( ...
    currentView, stage13.next_fault_state.state, rightShift, ...
    stage13.cseq2_complete_reschedule_search, ...
    config.completion_time_weights);

rightAudit = audit_stage_c_rescheduling_candidate( ...
    rightShift, stage13.next_fault, ...
    rightShift.interrupted_commitments, 'partial_right_shift');
front = stage13.cseq2_complete_reschedule_search.pareto_front;
completeAudits = repmat(rightAudit, 1, numel(front));
for index = 1:numel(front)
    completeAudits(index) = audit_stage_c_rescheduling_candidate( ...
        front(index).candidate, stage13.next_fault, ...
        stage13.cseq2_frozen_problem.interrupted_commitments, ...
        'complete_rescheduling');
end

result = struct();
result.stage = 'C-SEQ2';
result.step = 14;
result.config = config;
result.weight_sensitivity = weightAnalysis;
result.right_shift_energy_candidate = rightShift;
result.right_shift_audit = rightAudit;
result.complete_reschedule_audits = completeAudits;
result.data_provenance = build_data_provenance(stage13, projectRoot);
result.all_constraint_audits_validated = rightAudit.is_validated && ...
    all([completeAudits.is_validated]);
result.all_energy_audits_complete = ...
    rightAudit.energy_audit_complete && ...
    all([completeAudits.energy_audit_complete]);
result.multiseed_search_executed = false;
result.is_validated = weightAnalysis.is_validated && ...
    result.data_provenance.is_validated && ...
    result.all_constraint_audits_validated && ...
    result.all_energy_audits_complete;
end

function currentView = attach_current_plan_energy(currentView, scenario)
if isfield(currentView, 'agvEnergy') && ...
        isscalar(currentView.agvEnergy) && isfinite(currentView.agvEnergy)
    return
end
if isfield(scenario, 'plan_version_history') && ...
        isfield(scenario.plan_version_history, 'versions') && ...
        ~isempty(scenario.plan_version_history.versions)
    activePlan = scenario.plan_version_history.versions(end).plan;
    if isfield(activePlan, 'agv_energy') && ...
            isscalar(activePlan.agv_energy) && isfinite(activePlan.agv_energy)
        currentView.agvEnergy = activePlan.agv_energy;
    end
end
end

function provenance = build_data_provenance(stage13, projectRoot)
normalConfig = normal_schedule_config(projectRoot);
provenance = struct();
provenance.project_root = projectRoot;
provenance.raw_code_root = fullfile(projectRoot, 'raw_code');
provenance.instance_path = normalConfig.instancePath;
provenance.machine_data_path = normalConfig.machineDataPath;
provenance.agv_data_path = normalConfig.agvDataPath;
provenance.random_seed = normalConfig.seed;
provenance.problem_job_count = stage13.baseline.problem.jobNum;
provenance.problem_machine_count = stage13.baseline.problem.machineNum;
provenance.problem_operation_count = ...
    sum(stage13.baseline.problem.operaNumVec);
provenance.agv_count = stage13.baseline.agvData.AGVNum;
provenance.fault_event_source = ...
    'derived_from_current_source-data_schedule';
provenance.repair_duration_source = ...
    'experiment_parameter_applied_to_source-data_schedule';
provenance.search_budget_source = ...
    'experiment_parameter_not_problem_data';
provenance.source_data_only = true;
provenance.raw_code_modified = false;
provenance.synthetic_problem_data_created = false;
provenance.is_validated = exist(provenance.instance_path, 'file') == 2 && ...
    exist(provenance.machine_data_path, 'file') == 2 && ...
    exist(provenance.agv_data_path, 'file') == 2 && ...
    provenance.problem_job_count > 0 && ...
    provenance.problem_machine_count > 0 && ...
    provenance.problem_operation_count > 0 && ...
    provenance.agv_count > 0 && provenance.source_data_only && ...
    ~provenance.raw_code_modified && ...
    ~provenance.synthetic_problem_data_created;
end
