function combined = run_stage_b_combination_selection(searchScenario)
%RUN_STAGE_B_COMBINATION_SELECTION Reuse one completed Stage B search.
%   The complete search is not rerun. A deterministic linked right-shift
%   candidate is rebuilt from the exact same baseline and fault settings.

if nargin < 1 || ...
        ~isfield(searchScenario, 'complete_reschedule_search')
    error('run_stage_b_combination_selection:MissingSearch', ...
        'A scenario containing complete_reschedule_search is required.');
end

projectRoot = fileparts(fileparts(mfilename('fullpath')));
originalPath = path;
cleanupPath = onCleanup(@() path(originalPath));
addpath(fullfile(projectRoot, 'configs'));
addpath(fullfile(projectRoot, 'scripts'));
addpath(fullfile(projectRoot, 'src', 'evaluation'));
addpath(fullfile(projectRoot, 'src', 'rescheduling'));

rightScenario = run_stage_b_agv_linked_right_shift( ...
    searchScenario.baseline);
validate_same_scenario(searchScenario, rightScenario);

combined = rightScenario;
combined.complete_reschedule_search = ...
    searchScenario.complete_reschedule_search;
combined.combination_config = stage_b_combination_config();
combined.combined_selection = select_stage_b_combined_strategy( ...
    combined.baseline, combined.state, ...
    combined.linked_right_shift, ...
    combined.complete_reschedule_search, ...
    combined.combination_config);
combined.step = 12;
combined.is_combination_evaluated = true;
combined.is_validated = combined.is_validated && ...
    combined.combined_selection.is_validated;
end

function validate_same_scenario(searchScenario, rightScenario)
required = {'baseline', 'fault', 'resume_plan'};
for index = 1:numel(required)
    if ~isfield(searchScenario, required{index})
        error('run_stage_b_combination_selection:MissingField', ...
            'searchScenario.%s is required.', required{index});
    end
end

sameChromosome = isequal( ...
    searchScenario.baseline.chrom, rightScenario.baseline.chrom);
sameMakespan = abs(searchScenario.baseline.makespan - ...
    rightScenario.baseline.makespan) <= 1e-9;
sameFault = searchScenario.fault.machine_id == ...
    rightScenario.fault.machine_id && ...
    abs(searchScenario.fault.start_time - ...
    rightScenario.fault.start_time) <= 1e-9 && ...
    abs(searchScenario.fault.repair_end_time - ...
    rightScenario.fault.repair_end_time) <= 1e-9;
left = searchScenario.resume_plan;
right = rightScenario.resume_plan;
sameInterruptedOperation = left.job == right.job && ...
    left.operation == right.operation && ...
    left.machine_id == right.machine_id;
if ~sameChromosome || ~sameMakespan || ~sameFault || ...
        ~sameInterruptedOperation
    error('run_stage_b_combination_selection:ScenarioMismatch', ...
        ['Complete search and right shift must share one baseline, ', ...
        'fault, and interrupted operation.']);
end
end
